// Auto-generated by Hardhat deploy / sync script
import marketABI from './marketABI.json';
import vaultABI from './vaultABI.json';

export const Markets = [
    { address: "0x93bE5D9Eb826FfA8f973ec47483dFEC99dfAC482", abi: marketABI, title: "Market1" },
    { address: "0xeb04b9Af47DbcA4347BCAe3d044990008C7cb4d1", abi: marketABI, title: "Market2" },
    { address: "0xB539D626E7288e1E3c65DE8B485442a7fA551B1C", abi: marketABI, title: "Market3" },
];

export const Vaults = [
    { address: "0x1Fec355130943AbED730799Ed15fE893958AaA24", abi: vaultABI, title: "Vault1" },
    { address: "0xd44d13b95f7fC820856eb6E95A1DD17df9aEa07E", abi: vaultABI, title: "Vault2" },
];

export const Tokens = {
    USDC: "0x5eE4f82AD091DC5635C82998bc8333E1D89ee3e0",
    PryUSD: "0xc3A8730340C59ada20780867F95FA8D87c21a8DF",
    USDT: "0xD4Ab57054f012bF49abcB7C868431b17117349E3",
    USD1: "0x40Bbe7C4dB709Cd54F50f873F02Ce3ac800FE06E",
    DAI: "0x1B26Af61F71573Bd8B13E0c6787912aAe42Ef6A0",
};

export const DeployedAddresses = {
    "ProtocolModule#DAI": "0x1B26Af61F71573Bd8B13E0c6787912aAe42Ef6A0",
    "ProtocolModule#MarketImplementation": "0xf01a741aAa039627CEf3d3F1e4f680A488698F35",
    "ProtocolModule#PryUSD": "0xc3A8730340C59ada20780867F95FA8D87c21a8DF",
    "ProtocolModule#USD1": "0x40Bbe7C4dB709Cd54F50f873F02Ce3ac800FE06E",
    "ProtocolModule#USDC": "0x5eE4f82AD091DC5635C82998bc8333E1D89ee3e0",
    "ProtocolModule#USDT": "0xD4Ab57054f012bF49abcB7C868431b17117349E3",
    "ProtocolModule#VaultPryUSD": "0xd44d13b95f7fC820856eb6E95A1DD17df9aEa07E",
    "ProtocolModule#VaultUSDC": "0x1Fec355130943AbED730799Ed15fE893958AaA24",
    "ProtocolModule#ProxyMarketDAI": "0xB539D626E7288e1E3c65DE8B485442a7fA551B1C",
    "ProtocolModule#ProxyMarketUSD1": "0xeb04b9Af47DbcA4347BCAe3d044990008C7cb4d1",
    "ProtocolModule#ProxyMarketUSDT": "0x93bE5D9Eb826FfA8f973ec47483dFEC99dfAC482"
};
