import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const hardhatRoot = path.resolve(__dirname, "..");
const projectRoot = path.resolve(hardhatRoot, "..");

// Candidate frontend directories
function getCandidateFrontendServiceDirs(): string[] {
  return [
    path.join(projectRoot, "front", "src", "service"),
    path.join(projectRoot, "frontend", "src", "service"),
  ];
}

// 1. Sync ABIs from artifacts
export function syncAbisToFrontend() {
  const artifactsDir = path.join(hardhatRoot, "artifacts", "contracts");
  if (!fs.existsSync(artifactsDir)) {
    return;
  }

  const abiMappings: Record<string, string> = {
    "Market.sol/Market.json": "marketABI.json",
    "Vault.sol/Vault.json": "vaultABI.json",
    "tokens.sol/Token.json": "tokenABI.json",
    "tokens.sol/Share.json": "shareABI.json",
    "MyProxy.sol/MyProxy.json": "proxyABI.json",
  };

  const allAbis: Record<string, any> = {};

  for (const [relPath, outName] of Object.entries(abiMappings)) {
    const fullPath = path.join(artifactsDir, relPath);
    if (fs.existsSync(fullPath)) {
      const artifact = JSON.parse(fs.readFileSync(fullPath, "utf-8"));
      const contractName = outName.replace("ABI.json", "");
      allAbis[contractName] = artifact.abi;

      for (const serviceDir of getCandidateFrontendServiceDirs()) {
        if (fs.existsSync(serviceDir)) {
          fs.writeFileSync(path.join(serviceDir, outName), JSON.stringify(artifact.abi, null, 2));
        }
      }
    }
  }

  // Also write unified abis.json
  for (const serviceDir of getCandidateFrontendServiceDirs()) {
    if (fs.existsSync(serviceDir)) {
      fs.writeFileSync(path.join(serviceDir, "abis.json"), JSON.stringify(allAbis, null, 2));
      console.log(`[sync-frontend] All contract ABIs synced to: ${serviceDir}`);
    }
  }
}

// 2. Full Sync (ABIs + Deployed Addresses + contracts.js)
export function syncToFrontend(deploymentId?: string) {
  // First ensure ABIs are synced
  syncAbisToFrontend();

  const deploymentsDir = path.join(hardhatRoot, "ignition", "deployments");
  let targetFile = "";

  if (deploymentId) {
    const specificPath = path.join(deploymentsDir, deploymentId, "deployed_addresses.json");
    if (fs.existsSync(specificPath)) {
      targetFile = specificPath;
    }
  }

  if (!targetFile && fs.existsSync(deploymentsDir)) {
    // Pick the most recently modified deployment folder
    const entries = fs.readdirSync(deploymentsDir, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => {
        const filePath = path.join(deploymentsDir, d.name, "deployed_addresses.json");
        return {
          dir: d.name,
          filePath,
          mtime: fs.existsSync(filePath) ? fs.statSync(filePath).mtimeMs : 0,
        };
      })
      .filter((e) => e.mtime > 0)
      .sort((a, b) => b.mtime - a.mtime);

    if (entries.length > 0) {
      targetFile = entries[0].filePath;
    }
  }

  if (!targetFile || !fs.existsSync(targetFile)) {
    console.warn("[sync-frontend] No deployed_addresses.json found in", deploymentsDir);
    return;
  }

  console.log(`[sync-frontend] Reading addresses from: ${targetFile}`);
  const deployed = JSON.parse(fs.readFileSync(targetFile, "utf-8"));

  // Helper to extract address by matching key fragments
  const getAddr = (...patterns: (string | RegExp)[]) => {
    for (const key of Object.keys(deployed)) {
      for (const pattern of patterns) {
        if (typeof pattern === "string") {
          if (key.toLowerCase().includes(pattern.toLowerCase())) {
            return deployed[key];
          }
        } else if (pattern.test(key)) {
          return deployed[key];
        }
      }
    }
    return "";
  };

  const market1 = getAddr("ProxyMarketUSDT", "Market1");
  const market2 = getAddr("ProxyMarketUSD1", "Market2");
  const market3 = getAddr("ProxyMarketDAI", "Market3");

  const vault1 = getAddr("VaultUSDC", "Vault1");
  const vault2 = getAddr("VaultPryUSD", "Vault2");

  const usdc = getAddr("#USDC");
  const pryUsd = getAddr("#PryUSD");
  const usdt = getAddr("#USDT");
  const usd1 = getAddr("#USD1");
  const dai = getAddr("#DAI");

  let syncedCount = 0;

  for (const serviceDir of getCandidateFrontendServiceDirs()) {
    if (!fs.existsSync(serviceDir)) {
      continue;
    }

    // Generate contracts.js with all ABIs, Markets, Vaults, and Tokens
    const contractsJsContent = `// Auto-generated by Hardhat deploy / sync script
import marketABI from './marketABI.json';
import vaultABI from './vaultABI.json';
import tokenABI from './tokenABI.json';
import shareABI from './shareABI.json';
import proxyABI from './proxyABI.json';

// Export individual ABIs
export { marketABI, vaultABI, tokenABI, shareABI, proxyABI };

// Export unified ABIs dictionary
export const ABIs = {
    market: marketABI,
    vault: vaultABI,
    token: tokenABI,
    share: shareABI,
    proxy: proxyABI,
};

// Markets configuration
export const Markets = [
    { address: "${market1}", abi: marketABI, title: "Market1" },
    { address: "${market2}", abi: marketABI, title: "Market2" },
    { address: "${market3}", abi: marketABI, title: "Market3" },
];

// Vaults configuration
export const Vaults = [
    { address: "${vault1}", abi: vaultABI, title: "Vault1" },
    { address: "${vault2}", abi: vaultABI, title: "Vault2" },
];

// Token addresses
export const Tokens = {
    USDC: "${usdc}",
    PryUSD: "${pryUsd}",
    USDT: "${usdt}",
    USD1: "${usd1}",
    DAI: "${dai}",
};

// All deployed addresses
export const DeployedAddresses = ${JSON.stringify(deployed, null, 4)};
`;

    fs.writeFileSync(path.join(serviceDir, "contracts.js"), contractsJsContent);
    fs.writeFileSync(path.join(serviceDir, "deployedAddresses.json"), JSON.stringify(deployed, null, 2));

    console.log(`[sync-frontend] Successfully synced contracts.js and deployedAddresses.json to: ${serviceDir}`);
    syncedCount++;
  }

  if (syncedCount === 0) {
    console.warn("[sync-frontend] No frontend service directories found to sync.");
  }
}

// Auto-run if executed as script
if (process.argv.some((arg) => arg.includes("sync-frontend"))) {
  syncToFrontend();
}
