import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const hardhatRoot = path.resolve(__dirname, "..");
const projectRoot = path.resolve(hardhatRoot, "..");

export function syncToFrontend(deploymentId?: string) {
  // 1. Locate deployed_addresses.json
  const deploymentsDir = path.join(hardhatRoot, "ignition", "deployments");
  let targetFile = "";

  if (deploymentId) {
    const specificPath = path.join(deploymentsDir, deploymentId, "deployed_addresses.json");
    if (fs.existsSync(specificPath)) {
      targetFile = specificPath;
    }
  }

  if (!targetFile && fs.existsSync(deploymentsDir)) {
    // Pick the most recently modified deployment folder
    const entries = fs.readdirSync(deploymentsDir, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => {
        const filePath = path.join(deploymentsDir, d.name, "deployed_addresses.json");
        return {
          dir: d.name,
          filePath,
          mtime: fs.existsSync(filePath) ? fs.statSync(filePath).mtimeMs : 0,
        };
      })
      .filter((e) => e.mtime > 0)
      .sort((a, b) => b.mtime - a.mtime);

    if (entries.length > 0) {
      targetFile = entries[0].filePath;
    }
  }

  if (!targetFile || !fs.existsSync(targetFile)) {
    console.warn("[sync-frontend] No deployed_addresses.json found in", deploymentsDir);
    return;
  }

  console.log(`[sync-frontend] Reading addresses from: ${targetFile}`);
  const deployed = JSON.parse(fs.readFileSync(targetFile, "utf-8"));

  // Helper to extract address by matching key fragments
  const getAddr = (...patterns: (string | RegExp)[]) => {
    for (const key of Object.keys(deployed)) {
      for (const pattern of patterns) {
        if (typeof pattern === "string") {
          if (key.toLowerCase().includes(pattern.toLowerCase())) {
            return deployed[key];
          }
        } else if (pattern.test(key)) {
          return deployed[key];
        }
      }
    }
    return "";
  };

  const market1 = getAddr("ProxyMarketUSDT", "Market1");
  const market2 = getAddr("ProxyMarketUSD1", "Market2");
  const market3 = getAddr("ProxyMarketDAI", "Market3");

  const vault1 = getAddr("VaultUSDC", "Vault1");
  const vault2 = getAddr("VaultPryUSD", "Vault2");

  const usdc = getAddr("#USDC");
  const pryUsd = getAddr("#PryUSD");
  const usdt = getAddr("#USDT");
  const usd1 = getAddr("#USD1");
  const dai = getAddr("#DAI");

  // 2. Identify frontend candidate folders (front, frontend)
  const candidateDirs = [
    path.join(projectRoot, "front", "src", "service"),
    path.join(projectRoot, "frontend", "src", "service"),
  ];

  let syncedCount = 0;

  for (const serviceDir of candidateDirs) {
    if (!fs.existsSync(serviceDir)) {
      continue;
    }

    // 3. Sync ABIs from artifacts
    const marketArtifactPath = path.join(hardhatRoot, "artifacts", "contracts", "Market.sol", "Market.json");
    const vaultArtifactPath = path.join(hardhatRoot, "artifacts", "contracts", "Vault.sol", "Vault.json");

    if (fs.existsSync(marketArtifactPath)) {
      const marketArtifact = JSON.parse(fs.readFileSync(marketArtifactPath, "utf-8"));
      fs.writeFileSync(path.join(serviceDir, "marketABI.json"), JSON.stringify(marketArtifact.abi, null, 2));
    }

    if (fs.existsSync(vaultArtifactPath)) {
      const vaultArtifact = JSON.parse(fs.readFileSync(vaultArtifactPath, "utf-8"));
      fs.writeFileSync(path.join(serviceDir, "vaultABI.json"), JSON.stringify(vaultArtifact.abi, null, 2));
    }

    // 4. Generate contracts.js
    const contractsJsContent = `// Auto-generated by Hardhat deploy / sync script
import marketABI from './marketABI.json';
import vaultABI from './vaultABI.json';

export const Markets = [
    { address: "${market1}", abi: marketABI, title: "Market1" },
    { address: "${market2}", abi: marketABI, title: "Market2" },
    { address: "${market3}", abi: marketABI, title: "Market3" },
];

export const Vaults = [
    { address: "${vault1}", abi: vaultABI, title: "Vault1" },
    { address: "${vault2}", abi: vaultABI, title: "Vault2" },
];

export const Tokens = {
    USDC: "${usdc}",
    PryUSD: "${pryUsd}",
    USDT: "${usdt}",
    USD1: "${usd1}",
    DAI: "${dai}",
};

export const DeployedAddresses = ${JSON.stringify(deployed, null, 4)};
`;

    fs.writeFileSync(path.join(serviceDir, "contracts.js"), contractsJsContent);

    // Also write a raw JSON for convenience
    fs.writeFileSync(path.join(serviceDir, "deployedAddresses.json"), JSON.stringify(deployed, null, 2));

    console.log(`[sync-frontend] Successfully synced addresses and ABIs to: ${serviceDir}`);
    syncedCount++;
  }

  if (syncedCount === 0) {
    console.warn("[sync-frontend] No frontend service directories found to sync.");
  }
}

// Auto-run if executed as script
if (process.argv.some((arg) => arg.includes("sync-frontend"))) {
  syncToFrontend();
}
